### ISSUE TITLE
BMDB pages loading very slowly

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#14]
## 🐛 Describe the Bug

BMDB pages are loading extremely slowly today.  It is taking upwards of 20 to 45 seconds to navigate between tabs on an individual biomarker, or to go back to the main biomarkers page and search for another biomarker.

## 📜 How To Reproduce

Go to the main BMDB page at
https://bmdb.jpl.nasa.gov/biomarkers/

Search for any biomarker, for example EGFR or MUC1 or MMP1.
Once the biomarker finally appears in the search results list, click on the biomarker name.
Navigate between tabs (Basics, Organs, Studies, etc.)
Note how long this takes.

Bug appears when logged in. 

## 🔎 Expected Behavior

Should be faster. 

## 🖼 Screenshots

No screenshots. 

## 🕵️‍♀️ Extra Details

If you think it'll help, you can add any of the following:
-   Platform
    -   Desktop browser (macOS 10.15, Chrome or Firefox 76.0.1, etc.)
    -   Mobile (iOS 13.2 with Safari, etc.)
-   Time of day
    -   Error only happens between 2:30am and 4am, etc.
-   Additional context.
-   And so forth.

**Comment by nutjob4life** [comment]
This seems to have been intermittent. Focus BMDB is operating fine right now, and in fact seems faster than ever!
