### ISSUE TITLE
Three new protocols

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#30]
## 🥼 Protocol Request

(Sean, #435 and 439 have typos in the name in the DMCC.  I fixed the typos here.  Not sure if that will affect anything, since we won't be in synch with them. I'm going to email Royce to fix it. )

**Protocol ID:** 435
**Protocol Title:** Discovery of Cancer Biomarker 

**Protocol ID:** 438
**Protocol Title:** SPINK1 as a potential prostate cancer biomarker

**Protocol ID:** 439
**Protocol Title:** Utility of models incorporating urine biomarkers, T2:ERG and PCA3 in prostate cancer

**Comment by nutjob4life** [comment]
Yeah, the typos are fine. We can use any name we want so long as the ID numbers match.

Added 435, 438, and 439 👍

**Comment by mryan4** [comment]
Great, thanks!


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jan 13, 2021, at 9:12 AM, Sean Kelly <notifications@github.com> wrote:


Yeah, the typos are fine. We can use any name we want so long as the ID numbers match.

Added 435, 438, and 439 👍
