### ISSUE TITLE
Copy protocols from Organ tab to Studies tab

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#32]
## 🥼 Data Request

Hi Sean,

Please copy any and all protocols from the organ specific location (Organ tab) to the Studies tab, which is at the biomarker level.

In many cases the protocols are already in both locations, so before copying, check to see if the protocol is already on the Study tab (biomarker level).

Please let me know if you need any more details.

Thanks!

**Comment by nutjob4life** [comment]
@mryan4 I will need to do a brief restart and backup of bmdb.jpl.nasa.gov; the downtime should be minimal, like the blink of an eye

**Comment by nutjob4life** [comment]
Okay, done @mryan4 … here is the log output:

```console
Adding study 1 to biomarker 27
Adding study 251 to biomarker 1301
Adding study 251 to biomarker 1302
Adding study 251 to biomarker 1294
Adding study 251 to biomarker 1293
Adding study 251 to biomarker 1292
Adding study 209 to biomarker 1445
Adding study 305 to biomarker 48
Adding study 309 to biomarker 1233
Adding study 287 to biomarker 224
Adding study 303 to biomarker 1442
Adding study 234 to biomarker 968
Adding study 310 to biomarker 1421
Adding study 241 to biomarker 1128
Adding study 230 to biomarker 1263
Adding study 57 to biomarker 1264
Adding study 58 to biomarker 1265
Adding study 59 to biomarker 1266
Adding study 177 to biomarker 1267
Adding study 234 to biomarker 1270
Adding study 207 to biomarker 1271
Adding study 207 to biomarker 1272
Adding study 207 to biomarker 1273
Adding study 207 to biomarker 1274
Adding study 207 to biomarker 1275
Adding study 207 to biomarker 1276
Adding study 207 to biomarker 1277
Adding study 207 to biomarker 1278
Adding study 207 to biomarker 1279
Adding study 207 to biomarker 1280
Adding study 251 to biomarker 1290
Adding study 251 to biomarker 1291
Adding study 251 to biomarker 1295
Adding study 251 to biomarker 1296
Adding study 251 to biomarker 1297
Adding study 251 to biomarker 1298
Adding study 251 to biomarker 1299
Adding study 251 to biomarker 1300
Adding study 241 to biomarker 1303
Adding study 241 to biomarker 1304
Adding study 241 to biomarker 1305
Adding study 241 to biomarker 1306
Adding study 313 to biomarker 1307
Adding study 283 to biomarker 1310
Adding study 284 to biomarker 1311
Adding study 284 to biomarker 1312
Adding study 315 to biomarker 1313
Adding study 298 to biomarker 1328
Adding study 316 to biomarker 1163
Adding study 316 to biomarker 1353
Adding study 316 to biomarker 1363
Adding study 316 to biomarker 1375
Adding study 316 to biomarker 1383
Adding study 316 to biomarker 1092
Adding study 316 to biomarker 1392
Adding study 316 to biomarker 1398
Adding study 316 to biomarker 1404
Adding study 199 to biomarker 1362
Adding study 199 to biomarker 1314
Adding study 199 to biomarker 1315
Adding study 199 to biomarker 1316
Adding study 199 to biomarker 1317
Adding study 199 to biomarker 1318
Adding study 199 to biomarker 1319
Adding study 199 to biomarker 1320
Adding study 199 to biomarker 1325
Adding study 199 to biomarker 1321
Adding study 199 to biomarker 1322
Adding study 199 to biomarker 1323
Adding study 199 to biomarker 1324
Adding study 199 to biomarker 1326
Adding study 199 to biomarker 1327
Adding study 199 to biomarker 1329
Adding study 199 to biomarker 1330
Adding study 199 to biomarker 1331
Adding study 199 to biomarker 1332
Adding study 199 to biomarker 1333
Adding study 199 to biomarker 1334
Adding study 199 to biomarker 1335
Adding study 199 to biomarker 1336
Adding study 199 to biomarker 1337
Adding study 199 to biomarker 1338
Adding study 199 to biomarker 1339
Adding study 199 to biomarker 1340
Adding study 199 to biomarker 1341
Adding study 199 to biomarker 1342
Adding study 199 to biomarker 1343
Adding study 199 to biomarker 1344
Adding study 199 to biomarker 1345
Adding study 199 to biomarker 1346
Adding study 199 to biomarker 1347
Adding study 199 to biomarker 1348
Adding study 199 to biomarker 1349
Adding study 199 to biomarker 1350
Adding study 199 to biomarker 1351
Adding study 199 to biomarker 1352
Adding study 199 to biomarker 1354
Adding study 199 to biomarker 1355
Adding study 199 to biomarker 1356
Adding study 199 to biomarker 1357
Adding study 199 to biomarker 1358
Adding study 199 to biomarker 1359
Adding study 199 to biomarker 1360
Adding study 199 to biomarker 1361
Adding study 199 to biomarker 1364
Adding study 199 to biomarker 1365
Adding study 199 to biomarker 1366
Adding study 199 to biomarker 1367
Adding study 199 to biomarker 1368
Adding study 199 to biomarker 1369
Adding study 199 to biomarker 1370
Adding study 199 to biomarker 1371
Adding study 199 to biomarker 1372
Adding study 199 to biomarker 1373
Adding study 323 to biomarker 1269
Adding study 323 to biomarker 1268
Adding study 199 to biomarker 20
Adding study 199 to biomarker 1199
Adding study 314 to biomarker 1308
Adding study 314 to biomarker 1309
Adding study 206 to biomarker 1420
Adding study 215 to biomarker 1423
Adding study 324 to biomarker 1422
Adding study 305 to biomarker 1436
Adding study 237 to biomarker 1437
Adding study 286 to biomarker 1438
Adding study 286 to biomarker 1439
Adding study 286 to biomarker 1440
Adding study 303 to biomarker 1441
Adding study 303 to biomarker 1443
Adding study 317 to biomarker 1446
Adding study 320 to biomarker 1447
Adding study 318 to biomarker 1448
Adding study 207 to biomarker 1281
Adding study 207 to biomarker 1282
Adding study 268 to biomarker 1283
Adding study 268 to biomarker 1284
Adding study 268 to biomarker 1285
Adding study 268 to biomarker 1286
Adding study 268 to biomarker 1287
Adding study 78 to biomarker 127
Adding study 78 to biomarker 206
Adding study 80 to biomarker 1457
Adding study 230 to biomarker 78
Adding study 230 to biomarker 87
Adding study 234 to biomarker 229
Adding study 213 to biomarker 27
Adding study 213 to biomarker 913
Adding study 213 to biomarker 64
Adding study 213 to biomarker 192
Adding study 207 to biomarker 994
Adding study 207 to biomarker 1458
Adding study 207 to biomarker 979
Adding study 207 to biomarker 77
Adding study 265 to biomarker 1288
Adding study 265 to biomarker 1289
Adding study 199 to biomarker 606
Adding study 199 to biomarker 1203
Adding study 199 to biomarker 599
Adding study 199 to biomarker 1459
Adding study 199 to biomarker 1110
Adding study 199 to biomarker 1460
Adding study 199 to biomarker 524
Adding study 199 to biomarker 238
Adding study 199 to biomarker 167
Adding study 199 to biomarker 759
Adding study 262 to biomarker 540
Adding study 241 to biomarker 1203
Adding study 298 to biomarker 1040
Adding study 316 to biomarker 1462
Adding study 328 to biomarker 100
Adding study 287 to biomarker 1244
Adding study 287 to biomarker 1243
Adding study 287 to biomarker 54
Adding study 304 to biomarker 167
Adding study 322 to biomarker 1463
Adding study 321 to biomarker 1464
Adding study 302 to biomarker 1465
Adding study 309 to biomarker 104
Adding study 309 to biomarker 83
Adding study 307 to biomarker 27
Adding study 303 to biomarker 166
Adding study 323 to biomarker 664
Adding study 323 to biomarker 78
Adding study 323 to biomarker 1051
Adding study 325 to biomarker 970
Adding study 327 to biomarker 544
Adding study 325 to biomarker 86
Adding study 327 to biomarker 1051
Adding study 326 to biomarker 545
Adding study 325 to biomarker 546
Adding study 327 to biomarker 969
Adding study 180 to biomarker 1474
```

**Comment by mryan4** [comment]
This is AWESOME!!
I’m in a 2 hour training session, 11-1, which is why my replies are delayed.

But thank you so much.  I have struggled to get data into the BMDB over the years, mainly because I could not get investigators to provide me with the data.

So I’m thrilled to get all this data in there, get it entered and propagated.  I love when data is clean and robust (and of course, accurate!).



Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jan 26, 2021, at 11:24 AM, Sean Kelly <notifications@github.com> wrote:


Okay, done @mryan4 <https://github.com/mryan4> … here is the log output:

Adding study 1 to biomarker 27
Adding study 251 to biomarker 1301
Adding study 251 to biomarker 1302
Adding study 251 to biomarker 1294
Adding study 251 to biomarker 1293
Adding study 251 to biomarker 1292
Adding study 209 to biomarker 1445
Adding study 305 to biomarker 48
Adding study 309 to biomarker 1233
Adding study 287 to biomarker 224
Adding study 303 to biomarker 1442
Adding study 234 to biomarker 968
Adding study 310 to biomarker 1421
Adding study 241 to biomarker 1128
Adding study 230 to biomarker 1263
Adding study 57 to biomarker 1264
Adding study 58 to biomarker 1265
Adding study 59 to biomarker 1266
Adding study 177 to biomarker 1267
Adding study 234 to biomarker 1270
Adding study 207 to biomarker 1271
Adding study 207 to biomarker 1272
Adding study 207 to biomarker 1273
Adding study 207 to biomarker 1274
Adding study 207 to biomarker 1275
Adding study 207 to biomarker 1276
Adding study 207 to biomarker 1277
Adding study 207 to biomarker 1278
Adding study 207 to biomarker 1279
Adding study 207 to biomarker 1280
Adding study 251 to biomarker 1290
Adding study 251 to biomarker 1291
Adding study 251 to biomarker 1295
Adding study 251 to biomarker 1296
Adding study 251 to biomarker 1297
Adding study 251 to biomarker 1298
Adding study 251 to biomarker 1299
Adding study 251 to biomarker 1300
Adding study 241 to biomarker 1303
Adding study 241 to biomarker 1304
Adding study 241 to biomarker 1305
Adding study 241 to biomarker 1306
Adding study 313 to biomarker 1307
Adding study 283 to biomarker 1310
Adding study 284 to biomarker 1311
Adding study 284 to biomarker 1312
Adding study 315 to biomarker 1313
Adding study 298 to biomarker 1328
Adding study 316 to biomarker 1163
Adding study 316 to biomarker 1353
Adding study 316 to biomarker 1363
Adding study 316 to biomarker 1375
Adding study 316 to biomarker 1383
Adding study 316 to biomarker 1092
Adding study 316 to biomarker 1392
Adding study 316 to biomarker 1398
Adding study 316 to biomarker 1404
Adding study 199 to biomarker 1362
Adding study 199 to biomarker 1314
Adding study 199 to biomarker 1315
Adding study 199 to biomarker 1316
Adding study 199 to biomarker 1317
Adding study 199 to biomarker 1318
Adding study 199 to biomarker 1319
Adding study 199 to biomarker 1320
Adding study 199 to biomarker 1325
Adding study 199 to biomarker 1321
Adding study 199 to biomarker 1322
Adding study 199 to biomarker 1323
Adding study 199 to biomarker 1324
Adding study 199 to biomarker 1326
Adding study 199 to biomarker 1327
Adding study 199 to biomarker 1329
Adding study 199 to biomarker 1330
Adding study 199 to biomarker 1331
Adding study 199 to biomarker 1332
Adding study 199 to biomarker 1333
Adding study 199 to biomarker 1334
Adding study 199 to biomarker 1335
Adding study 199 to biomarker 1336
Adding study 199 to biomarker 1337
Adding study 199 to biomarker 1338
Adding study 199 to biomarker 1339
Adding study 199 to biomarker 1340
Adding study 199 to biomarker 1341
Adding study 199 to biomarker 1342
Adding study 199 to biomarker 1343
Adding study 199 to biomarker 1344
Adding study 199 to biomarker 1345
Adding study 199 to biomarker 1346
Adding study 199 to biomarker 1347
Adding study 199 to biomarker 1348
Adding study 199 to biomarker 1349
Adding study 199 to biomarker 1350
Adding study 199 to biomarker 1351
Adding study 199 to biomarker 1352
Adding study 199 to biomarker 1354
Adding study 199 to biomarker 1355
Adding study 199 to biomarker 1356
Adding study 199 to biomarker 1357
Adding study 199 to biomarker 1358
Adding study 199 to biomarker 1359
Adding study 199 to biomarker 1360
Adding study 199 to biomarker 1361
Adding study 199 to biomarker 1364
Adding study 199 to biomarker 1365
Adding study 199 to biomarker 1366
Adding study 199 to biomarker 1367
Adding study 199 to biomarker 1368
Adding study 199 to biomarker 1369
Adding study 199 to biomarker 1370
Adding study 199 to biomarker 1371
Adding study 199 to biomarker 1372
Adding study 199 to biomarker 1373
Adding study 323 to biomarker 1269
Adding study 323 to biomarker 1268
Adding study 199 to biomarker 20
Adding study 199 to biomarker 1199
Adding study 314 to biomarker 1308
Adding study 314 to biomarker 1309
Adding study 206 to biomarker 1420
Adding study 215 to biomarker 1423
Adding study 324 to biomarker 1422
Adding study 305 to biomarker 1436
Adding study 237 to biomarker 1437
Adding study 286 to biomarker 1438
Adding study 286 to biomarker 1439
Adding study 286 to biomarker 1440
Adding study 303 to biomarker 1441
Adding study 303 to biomarker 1443
Adding study 317 to biomarker 1446
Adding study 320 to biomarker 1447
Adding study 318 to biomarker 1448
Adding study 207 to biomarker 1281
Adding study 207 to biomarker 1282
Adding study 268 to biomarker 1283
Adding study 268 to biomarker 1284
Adding study 268 to biomarker 1285
Adding study 268 to biomarker 1286
Adding study 268 to biomarker 1287
Adding study 78 to biomarker 127
Adding study 78 to biomarker 206
Adding study 80 to biomarker 1457
Adding study 230 to biomarker 78
Adding study 230 to biomarker 87
Adding study 234 to biomarker 229
Adding study 213 to biomarker 27
Adding study 213 to biomarker 913
Adding study 213 to biomarker 64
Adding study 213 to biomarker 192
Adding study 207 to biomarker 994
Adding study 207 to biomarker 1458
Adding study 207 to biomarker 979
Adding study 207 to biomarker 77
Adding study 265 to biomarker 1288
Adding study 265 to biomarker 1289
Adding study 199 to biomarker 606
Adding study 199 to biomarker 1203
Adding study 199 to biomarker 599
Adding study 199 to biomarker 1459
Adding study 199 to biomarker 1110
Adding study 199 to biomarker 1460
Adding study 199 to biomarker 524
Adding study 199 to biomarker 238
Adding study 199 to biomarker 167
Adding study 199 to biomarker 759
Adding study 262 to biomarker 540
Adding study 241 to biomarker 1203
Adding study 298 to biomarker 1040
Adding study 316 to biomarker 1462
Adding study 328 to biomarker 100
Adding study 287 to biomarker 1244
Adding study 287 to biomarker 1243
Adding study 287 to biomarker 54
Adding study 304 to biomarker 167
Adding study 322 to biomarker 1463
Adding study 321 to biomarker 1464
Adding study 302 to biomarker 1465
Adding study 309 to biomarker 104
Adding study 309 to biomarker 83
Adding study 307 to biomarker 27
Adding study 303 to biomarker 166
Adding study 323 to biomarker 664
Adding study 323 to biomarker 78
Adding study 323 to biomarker 1051
Adding study 325 to biomarker 970
Adding study 327 to biomarker 544
Adding study 325 to biomarker 86
Adding study 327 to biomarker 1051
Adding study 326 to biomarker 545
Adding study 325 to biomarker 546
Adding study 327 to biomarker 969
Adding study 180 to biomarker 1474
