### ISSUE TITLE
Export list of biomarkers and Description field from Basics tab

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#33]
## 🥼 Data Request

Please generate a list of every biomarker record in the BMDB and the first 50 or so characters of the Description field (or the whole field, doesn't matter).  I just need to know which ones are blank, and which ones need to be updated. 

Please include Default name, HGNC name, Alternative Names, and Description.

Thanks!

**Comment by nutjob4life** [comment]
Working on this now; sorry for the delay @mryan4. You know how it goes: there are 30 priorities and they're all *top* 😖

**Comment by mryan4** [comment]
Yes, I totally understand. Thank you!


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jan 26, 2021, at 9:43 AM, Sean Kelly <notifications@github.com> wrote:


Working on this now; sorry for the delay @mryan4 <https://github.com/mryan4>. You know how it goes: there are 30 priorities and they're all top 😖

**Comment by nutjob4life** [comment]
Does this look all right?


[results.csv.zip](https://github.com/EDRN/biomarker-database/files/5874174/results.csv.zip)

**Comment by mryan4** [comment]
Yup, perfect. Thank you.
Close out that ticket!
😊


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jan 26, 2021, at 10:16 AM, Sean Kelly <notifications@github.com> wrote:


Does this look all right?

results.csv.zip <https://github.com/EDRN/biomarker-database/files/5874174/results.csv.zip>

**Comment by nutjob4life** [comment]
Closed! 🚪
