### ISSUE TITLE
Phase report - current BMDB phase vs Jackie's latest spreadsheet

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#34]
Hi Sean,

Could you re-run the report comparing the organ-phase-protocol of every biomarker currently in BMDB with the organ-phase-protocol information in Jackie's latest spreadsheet? 

I attempted to attach my stripped down version of Jackie's file here.  This will allow me to continue cleaning the data before the EDRN renewal and the BSA review.  I want to make sure phases are correct.

Thanks!!

[EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_Outside_withNewAdditions_Dec282020.xlsx](https://github.com/EDRN/biomarker-database/files/5926302/EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_Outside_withNewAdditions_Dec282020.xlsx)

**Comment by nutjob4life** [comment]
Removing the `data` tag (not a request to modify DB)

**Comment by nutjob4life** [comment]
@mryan4 sorry if I'm slow today, which tab is it in this Excel file? Is the the "collection protocols only"? I think last time you gave me a `.csv` file (which you can attach on GitHub by zipping it first).

**Comment by nutjob4life** [comment]
@mryan4 argh, I'm looking back over the report generator and it seems like the input is a CSV with these columns:

    name, organ, protocol ID, phase, principal investigator

If you could make that `.csv.zip` file and stick it here as a comment on the issue I think I can move forward.

**Comment by mryan4** [comment]
I thought I attached the version that has only one tab, with only 7 data columns.  I deleted everything else.

Here is the csv version of what I thought I attached.  Column G, DMCC Defined Current Phase of Biomarker, is the one to use in the comparison. 






Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Feb 4, 2021, at 11:49 AM, Sean Kelly <notifications@github.com> wrote:


@mryan4 <https://github.com/mryan4> sorry if I'm slow today, which tab is it in this Excel file? Is the the "collection protocols only"? I think last time you gave me a .csv file (which you can attach on GitHub by zipping it first).

**Comment by mryan4** [comment]
I just sent you the spreadsheet to use, in csv format.

The spreadsheet I sent you should be compared to the current data in the BMDB, which only you can access!
😊

Thanks. Let me know if you need anything else. 


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Feb 4, 2021, at 12:18 PM, Sean Kelly <notifications@github.com> wrote:


@mryan4 <https://github.com/mryan4> argh, I'm looking back over the report generator and it seems like the input is a CSV with these columns:

name, organ, protocol ID, phase, principal investigator
If you could make that .csv.zip file and stick it here as a comment on the issue I think I can move forward.

**Comment by mryan4** [comment]
How do I make a zip file?  Sorry, never had to do it.  I just unzip!


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Feb 4, 2021, at 12:18 PM, Sean Kelly <notifications@github.com> wrote:


@mryan4 <https://github.com/mryan4> argh, I'm looking back over the report generator and it seems like the input is a CSV with these columns:

name, organ, protocol ID, phase, principal investigator
If you could make that .csv.zip file and stick it here as a comment on the issue I think I can move forward.

**Comment by nutjob4life** [comment]
@mryan4 Oh okay, I restored some deleted files and found `EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_Outside_withNewAdditions_Dec282020_MRC.csv` with these columns: 

    Biomarker Name,Organ,Protocol ID,Current Phase,PI,DMCC Defined Protocol Phase,DMCC Defined Current Phase of Biomarker

If that looks right, attach an `.xlsx` file of just that tab with the new data you want me to run, or a `.csv.zip` file.

(To make a `.zip`. file, right click on its icon and choose `Compress` on a Mac.)

**Comment by mryan4** [comment]
Hopefully this works.  I zipped and drag/dropped. 

[EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_Outside_withNewAdditions_Dec282020_MRC.zip](https://github.com/EDRN/biomarker-database/files/5927459/EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_Outside_withNewAdditions_Dec282020_MRC.zip)

**Comment by nutjob4life** [comment]
I had to massage the data in the `.csv` to get the report to run

- The ® sign on "FOBT-CHEKOC®" got lost in translation
- DKK → DKK1
- DKK-3 → DKK3
- DKK- → DKK (no dash)
- DKK 1.00 → DKK1
- germline progressionÊ  → without the `Ê`
- Urine Proteomics UpgradingÊ → without the `Ê`
- Urine Proteomics Risk StratificationÊ → without the `Ê`
- Urine Proteomics DiagnosisÊ 
- Urine Proteomics ProgressionÊ
- Urine miRNA ProgressionÊ
- LSM 1.00 → LSM1
- LSM 7.00 → LSM7
- MDC 1.00 → MDC1
- PGK 1.00 → PGK1
- PGK 2.00 → PGK2

Anyway, after making those changes, the report produced 3 files, which are in the attached `.zip`. Hope you can make sense of it!
[issue-34-report.zip](https://github.com/EDRN/biomarker-database/files/5927555/issue-34-report.zip)

**Comment by mryan4** [comment]
Thanks!! I'll take a look.
Yes, there are several naming discrepancies in the spreadsheet. I will change them and make a note of it.
I'm still waiting for another update from Jackie, so we will have another round of these comparisons after I do the next wave of data entry.

**Comment by mryan4** [comment]
OK, that was not what I wanted.  I'm going to clean up the spreadsheet that I am sending you, and submit a new, hopefully more specific and clear, request.

Do you want me to add it here, or create a new issue?  It will take me until tomorrow to clean up all the naming issues and submit the new and improved request.

**Comment by nutjob4life** [comment]
I'm looking at the code and I see a later addition; this report takes as input a `.csv` file with these headings:

> Biomarker Name, Organ, Protocol ID, Phase, PI

Is that one familiar @mryan4?

**Comment by mryan4** [comment]
We have run so many reports, I want to make sure I ask you for exactly what I need. 
Once I'm done cleaning up the names, I am going to request a report that compares the biomarker-organ-protocol triplet in the file I send you (which originated with Jackie, i.e. the investigators) and ask that you compare it to every biomarker-organ-protocol triplet in the BMDB.

Names are always an issue.  I am trying to use the Default name, not HGNC name, since so many records will not have HGNC names. 

My purpose is to make sure that the phase data in the BMDB is correct, i.e. it matches Jackie's data. Her data is from the investiagators, so that is the gold standard as far as phase. They often have the names incorrect (ex: PRKC1 instead of PRKCI) so I need to fix her file before I send it to you.

Does that make sense?  There are so many ways to slice and dice the data to run these QC checks.  Thanks for your patience!

**Comment by nutjob4life** [comment]
Makes sense. I "eagerly" await the new triplets 😝

**Comment by mryan4** [comment]
The triplets are here!
I am attaching a csv file that originated from Jackie's spreadsheet (therefore the data is from the PIs). This is the gold standard - this is what we want the phases to be in the BMDB.  The column names all have 'from Jackie' appended so that I can tell where each column came from in your output file. 

Column A/Column C/Column E are the triplets.
BiomarkerName/ProtocolID/Phase

Please compare to the data currently in the BMDB.  You will still need to check default name, HGNC name, and synonyms for matches because the investigators use some *very* imaginative naming at times.  I include their creations in the synonyms, but I choose official and correct names for the Default, and obviously I choose HGNC names for HGNC.

What I am trying to do here is end up with a list that shows where the phase in BMDB does NOT match the attached csv file, for each triplet, so I can fix the data in BMDB.

(My next request will be for a report with the description field again, so I can see what is blank and continue to fill those in. Coming soon to a github request near you! )

Thank you thank you thank you thank you
:-) 


[EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_ForSeanEditedByMRC_OriginJackie_Feb052021.zip](https://github.com/EDRN/biomarker-database/files/5934451/EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_ForSeanEditedByMRC_OriginJackie_Feb052021.zip)

**Comment by nutjob4life** [comment]
@mryan4 okay things are finally quieting down enough after last week's crazy Artificial Intelligence workshop that I can look at this. Also, I temporarily have electric power, so now is a great time to make some progress!

Okay so when I build the triplets on the database side of things, I'm doing this:

- each biomarker name or alias plus the biomarker-study-data's FHCRC protocol ID plus the phase

So, as an example, consider biomarker 36, AFP: https://bmdb.jpl.nasa.gov/biomarkers/view/36

- It has 9 names
- When I click the studies tab, it's got 14 studies, each in a different phase

So that'll generate 126 triples, including

- AFP, SPORE/EDRN/PLCO Ovarian Validation Study (119), phase 2
- AFP, Validation of Serum Markers for the Early Detection of Hepatocellular Carcinoma (111), phase 2
- AFP, Breast Ref Applicant: Anu Mathew-Meso Scale (2012) (350), phase 3
- …
- Alpha-fetoglobulin,  SPORE/EDRN/PLCO Ovarian Validation Study (119), phase 2
- Alpha-fetoglobulin, Validation of Serum Markers for the Early Detection of Hepatocellular Carcinoma (111), phase 2
- Alpha-fetoglobulin, Breast Ref Applicant: Anu Mathew-Meso Scale (2012) (350), phase 3
- …

And so forth. I can then us your CSV's column A + column C + column E and find any differences plus any missing.

We are not considering organs this time around. That'll make things a lot easier!

**Comment by mryan4** [comment]
Hi Sean,

I wish it wasn’t so complicated (AFP is probably the most complicated) but yes, that sounds correct. 

You could just use the default name and HGNC name, and only use those 2 names (or 1 name, if no HGNC or if HGNC=default) for each biomarker.  

Most of the other synonyms will not be on Jackie’s list, so if using just default/HGNC for each biomarker makes it easier for you, please go ahead.  

Thank you!

Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Feb 15, 2021, at 5:34 PM, Sean Kelly <notifications@github.com> wrote:


@mryan4 <https://github.com/mryan4> okay things are finally quieting down enough after last week's crazy Artificial Intelligence workshop that I can look at this. Also, I temporarily have electric power, so now is a great time to make some progress!

Okay so when I build the triplets on the database side of things, I'm doing this:

each biomarker name or alias plus the biomarker-study-data's FHCRC protocol ID plus the phase
So, as an example, consider biomarker 36, AFP: https://bmdb.jpl.nasa.gov/biomarkers/view/36 <https://bmdb.jpl.nasa.gov/biomarkers/view/36>
It has 9 names
When I click the studies tab, it's got 14 studies, each in a different phase
So that'll generate 126 triples, including

AFP, SPORE/EDRN/PLCO Ovarian Validation Study (119), phase 2
AFP, Validation of Serum Markers for the Early Detection of Hepatocellular Carcinoma (111), phase 2
AFP, Breast Ref Applicant: Anu Mathew-Meso Scale (2012) (350), phase 3
…
Alpha-fetoglobulin, SPORE/EDRN/PLCO Ovarian Validation Study (119), phase 2
Alpha-fetoglobulin, Validation of Serum Markers for the Early Detection of Hepatocellular Carcinoma (111), phase 2
Alpha-fetoglobulin, Breast Ref Applicant: Anu Mathew-Meso Scale (2012) (350), phase 3
…
And so forth. I can then us your CSV's column A + column C + column E and find any differences plus any missing.

We are not considering organs this time around. That'll make things a lot easier!

**Comment by nutjob4life** [comment]
Had hand-edit to the EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_ForSeanEditedByMRC_OriginJackie_Feb052021.csv file so that "`FOBT-CHEKOK⚠️` got back its ® symbol which was lost somewhere between Excel, CSV, Zipping, extracting, and CSV parsing.

In addition, both the bmdb.jpl.nasa.gov database and the CSV file have various amounts of (mostly trailing, sometimes leading) whitespace in names, so I'm stripping that before making comparisons. Another issue is that capitalization varies, such as "N-Acetylglycine" (lower case G) in the DB but "N-AcetylGlycine" (upper case G) in the CSV file.

Anyway, here's the report. As an example of how to interpret it:

- Row 2: biomarker CDKN1C, the CSV file you sent says it's at phase 1 for protocol 377. In BMDB, though, 377 is at phase 0 (a/k/a "phase not set")
- Row 192: biomarker SPINK1, the CSV file says protocol is TBD. Im BMDB. it's protocol 438 at phase 1.
- Row 469: biomarker "Protein biomarkers" exists in the CSV file but is not found in BMDB.

Have fun with this!
[triples-correlation.csv.zip](https://github.com/EDRN/biomarker-database/files/5997807/triples-correlation.csv.zip)

**Comment by mryan4** [comment]
Thank you Sean!
I’m glad to see that you got your power back.  I hope you are staying safe and warm.


Maureen Ryan Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Feb 17, 2021, at 1:31 PM, Sean Kelly <notifications@github.com> wrote:


Had hand-edit to the EDRNBiomarkerPhases_UpdateDistributed_FinalCounts_ForSeanEditedByMRC_OriginJackie_Feb052021.csv file so that "FOBT-CHEKOK⚠️ got back its ® symbol which was lost somewhere between Excel, CSV, Zipping, extracting, and CSV parsing.

In addition, both the bmdb.jpl.nasa.gov database and the CSV file have various amounts of (mostly trailing, sometimes leading) whitespace in names, so I'm stripping that before making comparisons. Another issue is that capitalization varies, such as "N-Acetylglycine" (lower case G) in the DB but "N-AcetylGlycine" (upper case G) in the CSV file.

Anyway, here's the report. As an example of how to interpret it:

Row 2: biomarker CDKN1C, the CSV file you sent says it's at phase 1 for protocol 377. In BMDB, though, 377 is at phase 0 (a/k/a "phase not set")
Row 192: biomarker SPINK1, the CSV file says protocol is TBD. Im BMDB. it's protocol 438 at phase 1.
Row 469: biomarker "Protein biomarkers" exists in the CSV file but is not found in BMDB.
Have fun with this!
triples-correlation.csv.zip <https://github.com/EDRN/biomarker-database/files/5997807/triples-correlation.csv.zip>

**Comment by nutjob4life** [comment]
Thanks @mryan4! The power is still being rationed but luckily I was able to finish this when it was *on* 💡
