### ISSUE TITLE
Can't connect to BMDB phpMyAdmin

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#43]
## 🐛 Describe the Bug

I connected to the JPL VPN, then clicked on the bookmark that I have for phpMyAdmin, which is:
https://bmdb.jpl.nasa.gov/3rd-degree/index.php?route=/sql&server=1&db=cbmdb&table=biomarker_names&pos=0

And instead of seeing the login screen, I get an error message that says this:

![Screen Shot 2021-06-08 at 8 57 35 AM](https://user-images.githubusercontent.com/68615089/121196195-45d44980-c83e-11eb-8f4a-ea35f6b23ffa.png)

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Go to JPL VPN, log in

2. Go to BMDB phpMyAdmin at https://bmdb.jpl.nasa.gov/3rd-degree/index.php?route=/sql&server=1&db=cbmdb&table=biomarker_names&pos=0

3. See the error instead of the login screen

## 🔎 Expected Behavior

If you think it'll help, you can add any of the following:
-   Platform
    -   Firefox 88.0.1
    -   Chrome Version 91.0.4472.77

**Comment by nutjob4life** [comment]
Thanks for the thorough report @mryan4! 

I've diagnosed this as much as I can, and from what I can tell the issue is upstream and needs system administrator examination. I've submitted a ticket for the system administrators at: https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-345

**Comment by mryan4** [comment]
Thanks Sean!


Maureen Ryan
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jun 8, 2021, at 10:04 AM, Sean Kelly ***@***.***> wrote:


Thanks for the thorough report @mryan4 <https://github.com/mryan4>!

I've diagnosed this as much as I can, and from what I can tell the issue is upstream and needs system administrator examination. I've submitted a ticket for the system administrators at: https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-345 <https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-345>

**Comment by nutjob4life** [comment]
@mryan4 after a lot of haranguing, cajoling, quid pro quo, and mild bribery, this is back online:

https://bmdb.jpl.nasa.gov/3rd-degree/

**Comment by mryan4** [comment]
I just successfully logged in. Thank you!


Maureen Ryan
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Jun 8, 2021, at 1:48 PM, Sean Kelly ***@***.***> wrote:


@mryan4 <https://github.com/mryan4> after a lot of haranguing, cajoling, quid pro quo, and mild bribery, this is back online:

https://bmdb.jpl.nasa.gov/3rd-degree/ <https://bmdb.jpl.nasa.gov/3rd-degree/>
