### ISSUE TITLE
Not a bug, but BMDB is down

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#48]
## 🐛 Describe the Bug

Go to BMDB at 
https://bmdb.jpl.nasa.gov/

Get error message that says:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by nutjob4life** [comment]
Thanks for the report @mryan4.

The sysadmins at JPL are upgrading operating systems and moving services to new hosts. Focus BMDB is down as a result. I hope it comes back soon.

You can check on the status of things [at the Alleviam site](https://edrn.github.io/alleviam/).

**Comment by mryan4** [comment]
Darn.  OK, thanks.  I set a quota for myself for a certain number of Paulovich biomarkers/day, and I have not reached my quota today.
