### ISSUE TITLE
Request for report from BMDB

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#50]
## 🤔 Tell Us About the Feature

Hi Sean,

(I sent this as an email to your jpl address but it bounced back.)

I’m trying to put together some numbers/slides for the NCI at JPL meeting next week.
Can you still run reports from BMDB?  I know you don’t have VPN access right now.

I would just like a report with one line for every triple (biomarker-organ-protocol) in the database.

The fields I would like included are:

Biomarker ID
Biomarker Name
Organ
Protocol ID
Protocol Name
Phase (at the ORGAN-PROTOCOL level)

So for example, for AFP, the data exported would be: (I left off a couple, there were so many, and I truncated the protocol name just for this email)

36	AFP		Liver	111	Validation of Serum Markers…	Two
36	AFP		Liver	267	Liver Cancer Specimen Refer…	Three
36	AFP		Liver	285	Liver Reference Set: Block …	Three
36	AFP		Liver	319	Liver Reference Set: Block…		Three
36	AFP		Liver	336	Liver Reference Set Applican…	Three
36	AFP		Liver	334	Liver Reference Set (Full) Yam…	Three
36	AFP		Liver	311	Liver Ref Set: Lubman (Rapid…	Three
36	AFP		Liver	319	Liver Ref Set: Lubman (Rapid #2)	Three
36	AFP		Liver	327	LIver Reference Set (Rapid) Ya…	Three
36	AFP		Ovary	119	SPORE/EDRN/PLCO Ovarian Va	Three
36	AFP		Breast	350	Breast Ref Applicant: Anu Mathe	Three

I hope you still have the power!  And the time.  :-)

Thanks,
Maureen

**Comment by nutjob4life** [comment]
@mryan4 sorry, I don't have access anymore either 😭 

If by some miracle my access is restored, I'll run it.

**Comment by mryan4** [comment]
OK, thanks.  I was afraid of that. I just forwarded the email to your gmail and columbus accounts at Dan's suggestion.

**Comment by nutjob4life** [comment]
Ok thanks to @yuliujpl I have a copy of the database I can work with locally.

How does this look?

[report50.csv](https://github.com/EDRN/biomarker-database/files/9263232/report50.csv)

**Comment by mryan4** [comment]
Looks great!  I will investigate it a bit tomorrow and let you know if it needs any tweaks.  Thank you so much!

**Comment by mryan4** [comment]
OK I have a tweak already. :-)
I don't know what name field you are using, but could you please use the HGNC name for the second column, the one that is currently BM Name?  I should have specified. 
Thank you!

**Comment by nutjob4life** [comment]
@mryan4 okay how about now?
[report50.csv](https://github.com/EDRN/biomarker-database/files/9263352/report50.csv)

**Comment by mryan4** [comment]
Yes, thank you!  The previous one did not use the default name or the HGNC name, so I don't know where you were pulling from.  Appreciate it!
