### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biomarker-database#51]
[Moved from Portal to BMDB](https://github.com/EDRN/P5/issues/163) and re-filed for @mryan4:

Could you please run me a report with the following columns:
- Biomarker ID
- Biomarker HGNC Name
- Biomarker Default Name
- Description
- Publications
- Resources

This report is at the record level, i.e. BMDB says it contains 1416 biomarkers, so I would expect 1416 lines because I am not looking at any organ-level or protocol-level information. (I guess there will be more than 1416 lines because of multiple publications and resources per record, but I think you know what I am getting at?)

**Comment by nutjob4life** [comment]
@mryan4 let me know if this report looks okay or if there are changes you'd like

[report51.csv.zip](https://github.com/EDRN/biomarker-database/files/9921397/report51.csv.zip)

**Comment by mryan4** [comment]
Thank you!
I probably can’t look until next week now - I have suddenly become swamped by another project.  I will look ASAP and let you know. 


Maureen Ryan (Contractor)
Division of Gastroenterology & Hepatology 
Department of Medicine
UNC at Chapel Hill





On Nov 2, 2022, at 10:45 AM, Sean Kelly ***@***.***> wrote:


@mryan4 <https://github.com/mryan4> let me know if this report looks okay or if there are changes you'd like

report51.csv.zip <https://github.com/EDRN/biomarker-database/files/9921397/report51.csv.zip>

**Comment by nutjob4life** [comment]
Month old so closing as complete
