### ISSUE TITLE
Publications in BMDB do not match portal

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#56]
## 🐛 Describe the Bug

This is probably related to the CancerSEEK publication problem I reported a couple weeks ago. Publications on GPX1, for example, in BMDB are not the same as what is showing on GPX1 in the portal. 

## 📜 How To Reproduce

Link to GPX1 publications tab in BMDB: 
https://bmdb.jpl.nasa.gov/biomarkers/publications/437

Link to GPX1 publications tab on portal:
https://edrn.nci.nih.gov/data-and-resources/biomarkers/gpx1/

GPX3 has the same 2 publications in BMDB, and the same 2 INCORRECT publications on portal. 
ACKR3 also has wrong pubs on portal. Not same as GPX1 and GPX3.
HOXD1 also has wrong pubs on portal. Not same as any of the above.
Etc. 

## 🔎 Expected Behavior

Publications on the portal should reflect what is in BMDB. 

## 🖼 Screenshots

If you have any screenshots that help, attach them.

## 🕵️‍♀️ Extra Details

If you think it'll help, you can add any of the following:
-   Platform
    -   Desktop browser (macOS 10.15, Chrome or Firefox 76.0.1, etc.)
    -   Mobile (iOS 13.2 with Safari, etc.)
-   Time of day
    -   Error only happens between 2:30am and 4am, etc.
-   Additional context.
-   And so forth.

**Comment by nutjob4life** [comment]
Thanks @mryan4.

As you suspected, this was [a bug in the portal](https://github.com/EDRN/P5/issues/228). And it's already fixed, and is scheduled to go live into production at NCI as early as next week (2023-02-20).

You can see the correct publications at

- https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/biomarkers/gpx1/
- https://edrn-dev.nci.nih.gov/portal/renaissance/data-and-resources/biomarkers/gpx1/

I'm also attaching a screenshot:

<img width="1027" alt="Screenshot 2023-02-17 at 11 42 31 AM" src="https://user-images.githubusercontent.com/814813/219732404-78877ef8-7fc6-4199-badd-f9d07c441ee2.png">

**Comment by mryan4** [comment]
Great, thanks!! On Feb 17, 2023, at 12:47 PM, Sean Kelly ***@***.***> wrote:﻿
Thanks @mryan4.
As you suspected, this was a bug in the portal. And it's already fixed, and is scheduled to go live into production at NCI as early as next week (2023-02-20).
You can see the correct publications at

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/biomarkers/gpx1/
https://edrn-dev.nci.nih.gov/portal/renaissance/data-and-resources/biomarkers/gpx1/

I'm also attaching a screenshot:
