### ISSUE TITLE
Adding a publication in PROD gives Stack Trace error

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#64]
## 🐛 Describe the Bug

Was adding a publication to an existing biomarker record in the production version of BMDB on the Organs tab, within the Supporting Study Data -> Add Publication section. 

https://bmdb.jpl.nasa.gov/biomarkers/organs/1447/1562

![Screen Shot 2023-10-02 at 7 08 50 PM](https://github.com/EDRN/biomarker-database/assets/68615089/bdb8a6de-4cec-49b7-a23c-2674acc5cfa6)

![Screen Shot 2023-10-02 at 7 03 29 PM](https://github.com/EDRN/biomarker-database/assets/68615089/14e8d49c-8388-48e0-bef8-cd40ef30944a)

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. mtDNA Prostate Biomarkers 
https://bmdb.jpl.nasa.gov/biomarkers/view/1447

2. Go to the Organs tab
https://bmdb.jpl.nasa.gov/biomarkers/organs/1447/1562

3. See screenshots above. Add publication "Evaluation of two mitochondrial DNA biomarkers for prostate cancer detection"

4. Click 'Associate', Stack Trace error message appears.

## 🔎 Expected Behavior

Replace this with what you thought *should* happen.

## 🖼 Screenshots

If you have any screenshots that help, attach them.

## 🕵️‍♀️ Extra Details

If you think it'll help, you can add any of the following:
-   Platform
    -   Desktop browser (macOS 10.15, Chrome or Firefox 76.0.1, etc.)
    -   Mobile (iOS 13.2 with Safari, etc.)
-   Time of day
    -   Error only happens between 2:30am and 4am, etc.
-   Additional context.
-   And so forth.

**Comment by nutjob4life** [comment]
Deployed `edrndocker/edrn-bmdb:1.6.1` to production; can add/remove pubs
