### ISSUE TITLE
Remove various columns from organ_data

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biomarker-database#71]
## 🗑️ Data to Remove

Remove the following columns from the table `organ_data`:

- sensitivity_min
- sensitivity_max
- sensitivity_comment
- specificity_min
- specificity_max
- specificity_comment
- npv_min
- npv_max
- npv_comment
- ppv_min
- ppv_max
- ppv_comment

Discreet values for sensitivity, specificity, NPV, etc., are recorded at the biomarker-organ-study level. This may have once been used to aggregate the minimum and maximum values seen for each characteristic, however there is no longer any mention of these characteristics in the BMDB code.

The RDF generator has never used any of these columns.

## 📝 Code Modification?

- Biomarker database: no
- RDF generator: no

Recommend batch №2

Note: modifications to portal are not allowed; that means this information is in fact used and this table/column should be preserved.

## 💽 SQL

```sql
ALTER TABLE `organ_data`
    DROP COLUMN `sensitivity_min`,
    DROP COLUMN `sensitivity_max`,
    DROP COLUMN `sensitivity_comment`,
    DROP COLUMN `specificity_min`,
    DROP COLUMN `specificity_max`,
    DROP COLUMN `specificity_comment`,
    DROP COLUMN `npv_min`,
    DROP COLUMN `npv_max`,
    DROP COLUMN `npv_comment`,
    DROP COLUMN `ppv_min`,
    DROP COLUMN `ppv_max`,
    DROP COLUMN `ppv_comment`;
```

## 🩺 Testing Methodology

- RDF before/after comparison: yes
- In-app testing: yes
- Other: N/A

## 🧘 Acceptance

Sign off by @mryan4 by closing this issue

**Comment by mryan4** [comment]
No errors found during testing. This issue is closed.
