### ISSUE TITLE
Remove study_data.sensspecdetail

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biomarker-database#75]
## 🗑️ Data to Remove

Remove `study_data.sensspecdetail `. The database has 2 distinct values for this; one is blank. The other is `Results from analysis of clinical samples (50% sample).  Early stage (at minimum 12 months prior to ovarian cancer diagnosis), general population controls.`. How this latter one got in there is a mystery.

Regardless, neither BMDB nor the RDF generator use it.

## 📝 Code Modification?

- Biomarker database: no
- RDF generator: no

Batch №2 since batch №1 is getting full.

Note: modifications to portal are not allowed; that means this information is in fact used and this table/column should be preserved.

## 💽 SQL

```sql
ALTER TABLE `study_data` DROP COLUMN `sensspecdetail`;
```

## 🩺 Testing Methodology

- RDF before/after comparison: yes
- In-app testing: yes
- Other: N/A

## 🧘 Acceptance

Sign off by @mryan4 by closing this issue

**Comment by mryan4** [comment]
No errors found during testing. This issue is closed.
