### ISSUE TITLE
Remove table `users`

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biomarker-database#77]
## 🗑️ Data to Remove

Remove the table `users`. Apparently this may have been used to control access to the app before LDAP integration.

## 📝 Code Modification?

- Biomarker database: no
- RDF generator: no

Batch №1

Note: modifications to portal are not allowed; that means this information is in fact used and this table/column should be preserved.

## 💽 SQL

```sql
DROP TABLE `users`;
```

## 🩺 Testing Methodology

- RDF before/after comparison: yes
- In-app testing: yes
- Other: N/A

## 🧘 Acceptance

Sign off by @mryan4 by closing this issue

**Comment by mryan4** [comment]
No errors found during testing. This issue is closed.
